estoque_project/estoque/api/urls.py
from django.urls import path

from .. import views

app_name = "produto"

urlpatterns = [
    path("", views.ProdutoListView.as_view(), name="list"),
    path(
        "<int:pk>/",
        views.ProdutoDetailView.as_view(),
        name="detail"
    ),
    path("<int:pk>/edit/", views.ProdutoUpdateView.as_view(), name="update"),
    path("new/", views.ProdutoCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", views.ProdutoDeleteView.as_view(), name="delete"),
    path("orders/", views.OrdersListView.as_view(), name="carrinho"),
    path("orders/done/", views.FinishOrderView.as_view(), name="finish"),
    path("orders/add/<int:pk>/", views.NewOrderView.as_view(), name="add_order"),
    path("orders/update/", views.UpdateCarrinhoView.as_view(), name="update-carrinho"),
    path("orders/update/<int:pk>/", views.UpdateOrderView.as_view(), name="update_order"),
]

estoque_project/estoque_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', LoginView.as_view(), name="login"),
    path('admin/', admin.site.urls),
    path('user/', include('estoque.api.users_urls', namespace="user")),
    path('produtos/', include('estoque.api.urls', namespace="produto")),
    path('index/', include('estoque.api.users_urls', namespace="index")),
]

estoque_project/estoque/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime, timedelta
from django.contrib.auth.models import User


class Apedido(models.Model):
    apediid = models.AutoField(primary_key=True)
    acliid = models.ForeignKey(User, models.DO_NOTHING, db_column='acliid_id')
    apedidata = models.DateField(auto_now_add=True)
    apedistatus = models.SmallIntegerField(default=1)
    apedivenc = models.DateField(default=datetime.now() + timedelta(days=5))

    class Meta:
        managed = True
        db_table = 'apedido'


class Aproduto(models.Model):
    aprodid = models.AutoField(primary_key=True)
    aprodnome = models.CharField(max_length=255, verbose_name='Nome')
    aprodvalor = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Valor')
    aprodqntd = models.IntegerField(verbose_name='Quantidade')
    aprodativo = models.SmallIntegerField(verbose_name='Ativo')

    def __str__(self):
        return self.aprodnome

    def get_absolute_url(self):
        return reverse("produto:detail", kwargs={"pk": self.aprodid})

    class Meta:
        managed = True
        db_table = 'aproduto'
        verbose_name = 'Produto'


class Aprodutoinstancia(models.Model):
    aprinid = models.AutoField(primary_key=True)
    aprinid_acli = models.ForeignKey(User, models.DO_NOTHING, db_column="aprinid_acli")
    aprinid_apedi = models.ForeignKey(Apedido, models.DO_NOTHING, db_column="aprinid_apedi")
    aprinid_aprodid = models.ForeignKey(Aproduto, models.DO_NOTHING, db_column="aprinid_aprodid")
    aprinval = models.DecimalField(max_digits=10, decimal_places=2)
    aprinqnt = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'aprodutoinstancia'

estoque_project/estoque/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from .models import Aproduto


class ProductForm(forms.ModelForm):
    class Meta:
        model = Aproduto
        fields = [
            'aprodnome',
            'aprodvalor',
            'aprodqntd',
            'aprodativo',
        ]


class UserForm(forms.ModelForm):
    username = forms.CharField(min_length=8, label='Nome')
    password = forms.CharField(
        min_length=6,
        max_length=20,
        widget=forms.TextInput(attrs={'type': 'password'}),
        label='Senha'
    )
    email = forms.EmailField(required=True, label='Email')

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
        ]


class LoginForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(LoginForm, self).__init__(*args, **kwargs)

    acliemail = forms.EmailField(required=True, label='Email')
    aclipass = forms.CharField(
        min_length=6,
        max_length=20,
        widget=forms.TextInput(attrs={'type': 'password'}),
        label='Senha'
    )

    class Meta:
        model = User
        fields = [
            'acliemail',
            'aclipass',
        ]

estoque_project/estoque/views.py
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from django.views.generic import DeleteView, TemplateView, RedirectView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render, reverse, redirect
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from .forms import ProductForm, UserForm, LoginForm
from django.db.models import F
import sys
import json

from .models import Aproduto, Aprodutoinstancia, Apedido


@method_decorator(login_required, name='dispatch')
class ProdutoListView(ListView):
    template_name = 'estoque/aproduto_list.html'
    model = Aproduto

    def post(self, request, *args, **kwargs):
        email = request.POST.get('acliemail', '')
        password = request.POST.get('aclipass', '')
        if request.method == 'POST':
            try:
                actual_user = User.objects.get(acliemail=email)
            except:
                return redirect(reverse('login:login'))
            else:
                if password != actual_user.aclipass:
                    return redirect(reverse('login:login'))
            product = self.model.objects.all()
            return render(request, self.template_name, {'aproduto_list': product, 'user': email})


@method_decorator(login_required, name='dispatch')
class OrdersListView(LoginRequiredMixin, TemplateView):
    template_name = 'estoque/carrinho.html'
    model = Aprodutoinstancia

    def get_context_data(self, *args, **kwargs):
        context = super(OrdersListView, self).get_context_data(**kwargs)
        context['produtos'] = Aprodutoinstancia.objects.filter(
            aprinid_acli=self.request.user.id,
        )
        return context


@method_decorator(login_required, name='dispatch')
class ProdutoDetailView(DetailView):
    template_name = 'estoque/aproduto_detail.html'
    model = Aproduto

    def post(self, request, *args, **kwargs):
        print(request.POST.get('acliemail'))
        if request.method == 'POST':
            form = ProductForm(request.POST)

            if form.is_valid():
                return HttpResponseRedirect(f"/produtos/{self.kwargs['pk']}/")
        return render(request, self.template_name, {'pk': self.kwargs['pk']})


@method_decorator(login_required, name='dispatch')
class ProdutoUpdateView(UpdateView):
    template_name = 'estoque/aproduto_form.html'
    model = Aproduto
    form_class = ProductForm
    success_url = '/produtos/'

    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Aproduto, aprodid=id_)

    def form_valid(self, form):
        return super(ProdutoUpdateView, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class ProdutoCreateView(CreateView):
    template_name = 'estoque/aproduto_new.html'
    model = Aproduto
    form_class = ProductForm
    success_url = '/produtos/'

    def form_valid(self, form):
        return super(ProdutoCreateView, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class ProdutoDeleteView(DeleteView):
    model = Aproduto
    success_url = '/produtos/'

    def form_valid(self, form):
        return super(ProdutoDeleteView, self).form_valid(form)


class UserNewView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'estoque/acliente_form.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        return super(UserNewView, self).form_valid(form)


class LoginView(LoginView):
    model = User
    template_name = 'estoque/login.html'
    form_class = LoginForm
    redirect_field_name = '/produtos/'

    def form_valid(self, form):
        return super(LoginView, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class ProfileView(TemplateView):
    template_name = 'estoque/initial_page.html'


@method_decorator(login_required, name='dispatch')
class LogoutView(RedirectView):
    url = '/'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class NewOrderView(LoginRequiredMixin, CreateView):

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            prod = Aproduto.objects.get(pk=kwargs['pk'])
            user_email = request.user
            user_cliente = User.objects.get(username=user_email)
            new_pedido = Apedido.objects.create(acliid=user_cliente)
            new_pedido.save()
            Aprodutoinstancia.objects.create(
                aprinid_acli=user_cliente,
                aprinid_apedi=new_pedido,
                aprinid_aprodid=prod,
                aprinval=prod.aprodvalor,
                aprinqnt=1
            )
            pedido_inst_qnt = Aprodutoinstancia.objects.filter(
                aprinid_acli_id=user_cliente,
                aprinid_apedi_id=new_pedido,
                aprinid_aprodid_id=prod,
            ).values()[0]
            return JsonResponse({'pedId':new_pedido.apediid, 'pedQnt': pedido_inst_qnt})
            # newprod = Aproduto.objects.get(pk=kwargs['pk'])
            # return render(request, self.template_name, {'prod': prod, 'ped': new_pedido_inst, 'pednum': new_pedido})


@method_decorator(login_required, name='dispatch')
class UpdateOrderView(LoginRequiredMixin, UpdateView):

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            pedi_id = json.loads(request.body)['data']['pediId']
            pedi_inst = Apedido.objects.get(pk=pedi_id)
            prod = Aproduto.objects.get(pk=kwargs['pk'])
            user_email = request.user
            user_cliente = User.objects.get(username=user_email)
            Aprodutoinstancia.objects.create(
                aprinid_acli=user_cliente,
                aprinid_apedi=pedi_inst,
                aprinid_aprodid=prod,
                aprinval=prod.aprodvalor,
                aprinqnt=1
            )
            pedido_inst_qnt = Aprodutoinstancia.objects.filter(
                aprinid_acli_id=user_cliente,
                aprinid_apedi_id=pedi_id,
                aprinid_aprodid_id=prod,
            ).values()[0]
            return JsonResponse({'pedQnt':pedido_inst_qnt})

    def put(self, request, *args, **kwargs):
        if request.method == 'PUT':
            ped_inst_pk = json.loads(request.body)['data']['pedInst']
            pedi_id = json.loads(request.body)['data']['pediId']
            pedi_inst = Apedido.objects.get(pk=pedi_id)
            prod = Aproduto.objects.get(pk=kwargs['pk'])
            user_email = request.user
            user_cliente = User.objects.get(username=user_email)
            Aprodutoinstancia.objects.filter(
                aprinid=ped_inst_pk['pedQnt'],
                aprinid_acli_id=user_cliente,
                aprinid_apedi_id=pedi_id,
                aprinid_aprodid_id=prod,
            ).update(
                aprinqnt=F("aprinqnt") + 1,
                aprinval=prod.aprodvalor + (prod.aprodvalor * F("aprinqnt")),
            )
            return JsonResponse({'data': 'lallaa'})


@method_decorator(login_required, name="dispatch")
class UpdateCarrinhoView(LoginRequiredMixin, UpdateView):
    model = Aprodutoinstancia

    def get(self, request, *args, **kwargs):
        if request.method=='GET':
            ped_inst_pk = request.GET['aprinid']
            user_email = request.user
            user_cliente = User.objects.get(username=user_email)
            ped_inst_updated = self.model.objects.filter(
                aprinid=ped_inst_pk,
                aprinid_acli=user_cliente,
            ).all()
            return JsonResponse({ 'qnt': ped_inst_updated[0].aprinqnt, 'value': ped_inst_updated[0].aprinval})

    def put(self, request, *args, **kwargs):
        if request.method=='PUT':
            ped_inst_pk = json.loads(request.body)['data']['aprinid']
            method = json.loads(request.body)['data']['method']
            ped_inst = Aprodutoinstancia.objects.get(pk=ped_inst_pk)
            user_email = request.user
            user_cliente = User.objects.get(username=user_email)
            if method == 'increase':
                Aprodutoinstancia.objects.filter(
                    aprinid=ped_inst_pk,
                    aprinid_acli=user_cliente,
                ).update(
                    aprinqnt=F("aprinqnt") + 1,
                    aprinval=(F("aprinqnt") * ped_inst.aprinid_aprodid.aprodvalor)
                )
            elif method == 'decrease':
                Aprodutoinstancia.objects.filter(
                    aprinid=ped_inst_pk,
                    aprinid_acli=user_cliente,
                ).update(
                    aprinqnt=(F("aprinqnt") - 1),
                    aprinval=(F("aprinqnt") * ped_inst.aprinid_aprodid.aprodvalor)
                )
        return HttpResponse(status=200)


@method_decorator(login_required, name="dispatch")
class FinishOrderView(LoginRequiredMixin, UpdateView):
    model = Apedido

    def put(self, request, *args, **kwargs):
        user_email = request.user
        user_cliente = User.objects.get(username=user_email)
        pedi_id = json.loads(request.body)['data']['apediId']
        self.model.objects.filter(
            apediid=pedi_id,
            acliid=user_cliente,
        ).update(
            apedistatus=2,
        )
        return HttpResponse(status=200)


@method_decorator(login_required, name='dispatch')
class MyOrdersList(LoginRequiredMixin, ListView):
    model = Apedido

estoque_project/estoque/templates/estoque/acliente_form.html
{% extends 'estoque/base.html' %}

{% block content %}
<header>
    <h1>Cadastre um novo Usuário</h1>
</header>
<form action='' method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Cadastrar'>
</form>

{% endblock %}

estoque_project/estoque/templates/estoque/apedido_list.html
{% extends 'estoque/base.html' %}

{% block title %}Meus Pedidos{% endblock %}

{% block content %}
<header>
    <h1>Meus Pedidos</h1>
</header>
<a href="{% url 'index:index' %}"><button type="button">Página Inicial</button></a>
<p>Usuário: {{ request.user }}</p>
<article>
    <table>
        <thead>
            <th>Pedido Nº</th>
            <th>Data Pedido</th>
            <th>Status Pedido</th>
            <th>Data Vencimento</th>
        </thead>
        {% for pedido in pedidos %}
        <tbody>
            <td><a href="{% url 'user:detail-order' pk=pedido.apediid %}">{{ pedido.apediid }}</a></td>
            <td>{{ pedido.apedidata|date:"M d, Y" }}</td>
            <td>{{ pedido.apedistatus }}</td>
            <td>{{ pedido.apedivenc|date:"M d, Y" }}</td>
        </tbody>
        {% endfor %}
    </table>
</article>
{% endblock %}

estoque_project/estoque/templates/estoque/aproduto_confirm_delete.html
{% extends "estoque/base.html" %}

{% block title %}{{ aproduto.aprodutonome }}{% endblock %}

{% block content %}
    <header>
        <h1>Confirmar exclusão</h1>
    </header>
<form action="" method="POST">
    {% csrf_token %}
    <ul>
        <li>Nome: {{aproduto.aprodnome}}</li>
        <li>Valor: {{aproduto.aprodvalor}}</li>
        <li>Quantidade: {{aproduto.aprodqntd}}</li>
        <li>Ativo: {{aproduto.aprodativo}}</li>
    </ul>
    <input type="submit" value="Confirmar exclusão">
</form>
<a href="{% url 'produto:list' %}"><button type="button">Voltar</button></a>
{% endblock %}

estoque_project/estoque/templates/estoque/aproduto_detail.html
{% extends "estoque/base.html" %}

{% block title %}{{ aproduto.aprodutonome }}{% endblock %}

{% block content %}
    <header>
        <h1>Detalhes do Produto</h1>
    </header>
    <p>
        Nome: {{ aproduto.aprodnome }}
    </p>
    <p>
        Valor: {{ aproduto.aprodvalor }}
    </p>
    <p>
        Quantidade: {{ aproduto.aprodqntd }}
    </p>
    <p>
        Ativo: {{ aproduto.aprodativo }}
    </p>
    <a href="{% url 'produto:update' aproduto.aprodid %}" >Editar Produto</a>
{% endblock %}

estoque_project/estoque/templates/estoque/aproduto_form.html
{% extends 'estoque/base.html' %}

{% block content %}
<header>
    <h1>Atualize as informações</h1>
</header>
<form action='' method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Atualizar'>
</form>

{% endblock %}

estoque_project/estoque/templates/estoque/aproduto_list.html
{% extends "estoque/base.html" %}

{% block title %}Lista de Produtos{% endblock %}


{% block content %}
<header>
    <h1>Lista de Produtos</h1>
</header>
<a href="{% url 'index:index' %}"><button type="button">Página Inicial</button></a>
<a href="{% url 'produto:create' %}"><button type="button">Criar Produto</button></a>
<div class="container-carrinho">
    <a href="{% url 'produto:carrinho' %}"><button type="button">Carrinho de compras</button></a>
    <div id="carrinho-qntd">0</div>
</div>
<p>Usuário: {{ request.user }}</p>
{% csrf_token %}
<article>
    <table>
        <thead>
            <th>Produto</th>
            <th>Valor</th>
            <th>Quantidade</th>
            <th>Ativo</th>
            <th>Remover Produto</th>
            <th>Adicionar ao Carrinho</th>
        </thead>
        {% for produto in aproduto_list %}
        <tbody>
            <td><a href="{{ produto.get_absolute_url }}">{{ produto.aprodnome }}</a></td>
            <td>{{ produto.aprodvalor }}</td>
            <td>{{ produto.aprodqntd }}</td>
            <td>{{ produto.aprodativo}}</td>
            <td>
                <a href="{% url 'produto:delete' pk=produto.aprodid %}">
                    <button type="button">X</button>
                </a>
            </td>
            <td>
                <button type="button" onclick="orderList(event)" value="{{ produto.aprodid }}">
                    Adicionar
                </button>
            </td>
        </tbody>
        {% endfor %}
    </table>
</article>

{% endblock %}

estoque_project/estoque/templates/estoque/aproduto_new.html
{% extends 'estoque/base.html' %}

{% block content %}
<header>
    <h1>Crie seu produto</h1>
</header>
<form action='' method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Criar'>
</form>

{% endblock %}

estoque_project/estoque/templates/estoque/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <title>{% block title %}{% endblock %}</title>
    <script src="{% static 'main.js' %}" type="text/javascript"></script>
    <link href="{% static 'style.css' %}" rel="stylesheet"></link>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.0/axios.min.js" type="text/javascript"></script>
</head>

<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>

</html>

estoque_project/estoque/templates/estoque/carrinho.html
{% extends 'estoque/base.html' %}
{% block title %}Carrinho de Compras{% endblock %}
{% block content %}
<header>
    <h1>Carrinho de Compras</h1>
</header>
<nav>
    <div>
        <p>
            Usuário: {{ request.user }}
        </p>
    </div>
    <div>
        <a href="{% url 'index:index' %}"><button type="button">Página Inicial</button></a>
        <a href="{% url 'produto:list' %}"><button type="button">Lista de Produtos</button></a>
    </div>
</nav>
{% csrf_token %}
<article>
    <table>
        <thead>
            <th>Nome</th>
            <th>Valor</th>
            <th>Quantidade</th>
        </thead>
        {% for item in produtos %}
        {% if item.aprinid_apedi.apedistatus == 1 %}
        <tbody>
            <td>{{ item.aprinid_aprodid.aprodnome }}</td>
            <td id="val-span{{item.aprinid}}">{{item.aprinval}}</td>
            <td>
                <button type="button" onclick="increaseQnt(event)" value="{{item.aprinid}}">+</button>
                <span id="qnt-span{{item.aprinid}}">{{ item.aprinqnt }}</span>
                <button type="button" onclick="decreaseQnt(event)" value="{{item.aprinid}}">-</button>
            </td>
        </tbody>
        {% endif %}
        {% endfor %}
    </table>
    <div>
        <a><button type="submit" onclick="finishOrder(event)" value="{{item.aprinid}}">Finalizar compra</button></a>
    </div>
</article>
{% endblock %}

estoque_project/estoque/templates/estoque/initial_page.html
{% extends "estoque/base.html" %}

{% block title %}Pedidos{% endblock %}

{% block content %}
<h1>Painel de controle</h1>
<article>
    <a href="{% url 'produto:list' %}"><button type="button">Lista de Produtos</button></a>
    <a href="{% url 'user:my-orders'  %}"><button type="button">Meus Pedidos</button></a>
    <a href="{% url 'produto:carrinho' %}"><button type="button">Carrinho de Compras</button></a>
    <a href="{% url 'user:logout' %}"><button type="button">Logout</button></a>
</article>
{% endblock %}

estoque_project/estoque/templates/estoque/order_detail.html
{% extends 'estoque/base.html' %}

{% block title %}Detalhes do Pedido{% endblock %}

{% block content %}
<header>
    <h1>Detalhes do Pedido</h1>
</header>
<nav>
    <div>
        <p>
            Usuário: {{ request.user }}
        </p>
    </div>
    <div>
        <a href="{% url 'index:index' %}"><button type="button">Página Inicial</button></a>
        <a href="{% url 'produto:list' %}"><button type="button">Lista de Produtos</button></a>
        <a href="{% url 'user:my-orders'  %}"><button type="button">Meus Pedidos</button></a>
    </div>
</nav>
<article>
    <table>
        <thead>
            <th>Nome</th>
            <th>Valor</th>
            <th>Quantidade</th>
        </thead>
        {% for item in order_list %}
        <tbody>
            <td>{{ item.aprinid_aprodid.aprodnome }}</td>
            <td id="val-span{{item.aprinid}}">{{item.aprinval}}</td>
            <td>
                <span id="qnt-span{{item.aprinid}}">{{ item.aprinqnt }}</span>
            </td>
        </tbody>
        {% endfor %}
    </table>
    <div>
        <h2>Data:</h2>
        <p>{{ order_list.0.aprinid_apedi.apedidata }}</p>
    </div>
</article>
{% endblock %}

estoque_project/estoque/templates/estoque/orders_list.html
{% extends 'estoque/base.html' %}
{% block content %}
<aside>
    <div>
        <div>
            <p>Pedido Id: <span id="apediid">{{ order_list.get_context_data}}</span></p>
        </div>
        <table>
            <thead>
                <th>Produto</th>
                <th>Valor</th>
                <th>Quantidade</th>
            </thead>
            <tbody>
            {% for produto in produtos_pedido %}
                <tr>
                    <td><a href="{{ produto.get_absolute_url }}">{{ produto.aprinid_apro.aprodnome }}</a></td>
                    <td>{{ produto.aprinval }}</td>
                    <td>{{ produto.aprinqnt }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</aside>
{% endblock %}